<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIoJ9LWo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIoJ9LWo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIoJ9LWo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIoJ9LWo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIoJ9LWo\App_KernelDevDebugContainer([
    'container.build_hash' => 'IoJ9LWo',
    'container.build_id' => '0601fef1',
    'container.build_time' => 1650241181,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIoJ9LWo');
